### PR TITLE
fix/nullability-of-fields-not-extracted

### PR DESCRIPTION
**Pull request by DomasM**
Fix for #58 
Do not presume nullability when creating an instance of FieldInfo.

### CODE REVIEW

**Comment by k94ll13nn3** [comment]
Thanks, I did miss that when I did the work on base constructor !
Can you fix the warnings before I merge ? (I fixed the warnings not related to your modifications on master so you may want to rebase).

**Comment by DomasM** [comment]
rebased, there were no warnings to fix.

**Comment by k94ll13nn3** [comment]
Weird, there is some warnings [here](https://github.com/k94ll13nn3/AutoConstructor/pull/59/files), but it's nothing major.

**Comment by DomasM** [comment]
@k94ll13nn3  sorry, I thought you were talking about Visual Studio analyze solution warnings

**Pull request merged**
